### ISSUE TITLE
json file from config file 

### ISSUE THREAD

**Issue by soad1982** [remiyazigi/pc_process#16]
https://github.com/remiyazigi/pc_process/blob/cff1f9edc3cf8be44f8f357fd5ad7aeafb218ef5/src/spreadsheet.py#L93

**Comment by remiyazigi** [comment]
done

**Comment by soad1982** [comment]
we need to start getting a process together, for each issue you need to a new commit and a PR so we can talk about it and get the right code into the master branch. I will make a small change and leave the PR open so you can review it.

**Comment by soad1982** [comment]
You say is done, but the example config file does not have the new format, I can not test this.

**Comment by remiyazigi** [comment]
updated
