### ISSUE TITLE
Passed controls

### ISSUE THREAD

**Issue by soad1982** [remiyazigi/pc_process#18]
Can we know or infer somehow the number of controls that the host did pass? I'm thinking about a pass vs failed graph, that would be a good over time chart. Qualys is supposed to have one but it does not work at all.

https://github.com/remiyazigi/pc_process/blob/4fbeca30d2a14468e21404ad7580aba62ceef39b/src/spreadsheet.py#L42

**Comment by remiyazigi** [comment]
function spreadsheet.passed() returns the number of passed controls
