### ISSUE TITLE
PR process

### ISSUE THREAD

**Issue by soad1982** [remiyazigi/pc_process#27]
this file is still on the repo, remove it https://github.com/remiyazigi/pc_process/blob/master/src/authentication.pyc

Also, we need to start with the process, so create Pull requests and require review so we can start merging to master only after the code has been reviewed.

**Comment by remiyazigi** [comment]
i still don't know how this thing is getting here i have a gitignore *.pyc
i have been creating pull requests but but i was merging  them before you review, i will wait for your review
